title: HimitsuShell Blog
description: "Shell 脚本保护器（代码混淆、DRM）。技术文章、安全分析。"
url: "https://himitsushell.github.io"
theme: minima
lang: zh-CN
author: HimitsuShell
email: hjyun@mushsw.com

show_excerpts: true
github_username: HimitsuShell

kramdown:
  syntax_highlighter_opts:
    theme: github

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap